// Use the isolated test browser: this script exercises local saved exploration.
import assert from 'node:assert/strict'
import { createBrowserSession } from './helpers/browser-session.mjs'
process.env.FLEXBOX_TEST_ORIGIN ||= 'http://127.0.0.1:8765'
process.env.FLEXBOX_CDP_ORIGIN ||= 'http://127.0.0.1:9229'
process.env.FLEXBOX_SCREENSHOTS ||= '.raid-checks/character-encoding'
const s = await createBrowserSession({ lessonPath: '/pages/topics/character-sets-ascii-and-unicode.html', readyExpression: 'document.querySelector("[data-teacher-opener-slide]") && document.querySelector("[data-character-inspector=ascii] [data-inspector-live]").hidden === false' })
const frame = () => s.ev('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))')
const click = async selector => { await s.click(selector); await frame() }
const fit = async id => {
  const size = await s.ev(`(()=>{const e=document.getElementById('${id}');return {h:e.clientHeight,sh:e.scrollHeight,w:e.clientWidth,sw:e.scrollWidth}})()`)
  if (size.sh > size.h + 2 || size.sw > size.w + 2) await s.screenshot(`overflow-${id}`)
  assert.ok(size.sh <= size.h + 2 && size.sw <= size.w + 2, `${id}: ${JSON.stringify(size)}`)
}
const goto = async id => {
  for (let i=0;i<35;i++) {
    if (await s.ev(`location.hash === '#${id}'`)) return
    await click('[data-action=next-slide]')
  }
  throw new Error(`Could not reach ${id}`)
}
try {
  await s.send('Runtime.enable'); await s.send('Log.enable'); await s.send('Page.enable')
  await s.send('Emulation.setDeviceMetricsOverride', {width:1366,height:768,deviceScaleFactor:1,mobile:false})
  await s.send('Emulation.setEmulatedMedia', {features:[{name:'prefers-reduced-motion',value:'reduce'}]})
  await s.load()
  assert.deepEqual(await s.ev('[...document.querySelectorAll(".text-message-mapping > strong")].map(e=>e.textContent)'), ['h','e','l','l','o'])
  assert.deepEqual(await s.ev('[...document.querySelectorAll(".text-message-mapping > code")].map(e=>e.textContent)'), ['00','01','10','10','11'])
  assert.equal(await s.ev('document.querySelectorAll("[data-exam-response]").length'), 3)
  assert.equal(await s.ev('document.querySelectorAll("[data-practice-bytes], [data-character-inspector=ascii] [data-inspector-reset]").length'), 0)
  assert.ok(await s.ev('[...document.querySelectorAll(".quiz-answer-list")].every(e=>getComputedStyle(e).display==="grid" && parseFloat(getComputedStyle(e).rowGap)>=9)'), 'Quiz answer spacing uses the shared grid pattern')
  await s.ev(`localStorage.removeItem('education-tools:character-sets-ascii-and-unicode-teacher-mode');localStorage.setItem('education-tools:lesson-character-sets-inspector',JSON.stringify({text:'Earlier £ text'}));`)
  await s.load()
  assert.equal(await s.ev('document.querySelector("[data-inspector-input]").value'), 'Hi!', 'Teaching starts predictably despite previous work')
  await click('[data-action=toggle-teacher-mode]')
  await goto('encode-decode')
  await s.waitFor('document.querySelector("[data-character-transmission]").dataset.transmissionReady === "true"')
  assert.match(await s.text('[data-transmission-count]'), /0 \/ 5/)
  for (let step=1;step<=5;step++) {
    await click('[data-transmission-next]')
    assert.equal(await s.ev('[...document.querySelectorAll("[data-transmission-letter].has-arrived")].map(e=>e.textContent).join("")'), 'hello'.slice(0,step))
    await fit('encode-decode')
  }
  await click('[data-transmission-next]')
  assert.match(await s.text('[data-transmission-count]'), /5 \/ 5/)
  await click('[data-transmission-restart]')
  await click('[data-transmission-play]')
  await s.waitFor('parseFloat(document.querySelector("[data-transmission-packet]").style.left)>8')
  await click('[data-transmission-play]')
  const pausedPosition = await s.ev('document.querySelector("[data-transmission-packet]").style.left')
  await s.ev('new Promise(resolve=>setTimeout(resolve,250))')
  assert.equal(await s.ev('document.querySelector("[data-transmission-packet]").style.left'),pausedPosition)
  await s.screenshot('transmission-paused')
  await click('[data-transmission-play]')
  await s.waitFor('document.querySelectorAll("[data-transmission-letter].has-arrived").length>=1')
  await click('[data-action=next-slide]')
  await s.waitFor('document.querySelector("[data-transmission-play]").getAttribute("aria-pressed")==="false"')
  const stoppedCount=await s.text('[data-transmission-count]')
  await s.ev('new Promise(resolve=>setTimeout(resolve,250))')
  assert.equal(await s.text('[data-transmission-count]'),stoppedCount,'Leaving the slide pauses transmission')
  await click('[data-action=prev-slide]')
  await click('[data-transmission-restart]')
  for(let i=0;i<4;i++)await click('[data-transmission-next]')
  await click('[data-transmission-play]')
  await s.waitFor('document.querySelectorAll("[data-transmission-letter].has-arrived").length===5')
  assert.equal(await s.text('[data-transmission-play]'),'Play again')
  assert.equal(await s.ev('document.querySelector("[data-transmission-packet]").hidden'),true)
  await s.screenshot('transmission-complete')
  await click('[data-transmission-restart]')
  await goto('ascii-table')
  await s.ev(`document.querySelector('[data-character-inspector=ascii] [data-character-index="1"]').focus()`)
  await click('[data-character-inspector=ascii] [data-character-index="1"]')
  assert.match(await s.text('[data-character-inspector=ascii] [data-inspector-card]'), /97/)
  assert.match(await s.text('[data-character-inspector=ascii] [data-inspector-card]'), /1100001/)
  assert.equal(await s.ev('document.activeElement.dataset.characterIndex'), '1', 'Selection updates preserve button focus')
  await fit('ascii-table')
  await goto('utf8')
  assert.equal(await s.ev('document.querySelectorAll("#utf8 [data-walkthrough-step]").length'),0)
  assert.deepEqual(await s.ev('[...document.querySelectorAll("#utf8 .text-byte")].map(e=>e.textContent)'),['C3','A9'])
  await fit('utf8'); await s.screenshot('utf8-overview')
  await goto('decoding')
  await s.input('[data-decoder]','windows-1252'); await frame()
  assert.equal(await s.text('[data-decoded-text]'), 'cafÃ©')
  assert.match(await s.text('[data-decoder-status]'), /C3 as Ã and A9 as ©/)
  await fit('decoding'); await s.screenshot('decoder-mismatch')
  await click('[data-decoder-reset]')
  assert.equal(await s.text('[data-decoded-text]'), 'café')
  await goto('inspector')
  await click('[data-inspector-restore]')
  assert.equal(await s.ev('document.querySelector("[data-inspector-input]").value'), 'Earlier £ text')
  await click('[data-inspector-sample="Aé漢😀"]')
  assert.match(await s.text('[data-character-inspector=utf8] [data-inspector-status]'), /4 code points · 10 UTF-8 bytes/)
  await click('[data-character-inspector=utf8] [data-character-index="3"]')
  assert.deepEqual(await s.ev('[...document.querySelectorAll("[data-character-inspector=utf8] [data-inspector-card] .text-byte")].map(e=>e.textContent)'), ['F0','9F','98','80'])
  await fit('inspector'); await s.screenshot('inspector-emoji')
  await click('[data-character-inspector=utf8] [data-inspector-reset]')
  assert.equal(await s.ev('JSON.parse(localStorage.getItem("education-tools:lesson-character-sets-inspector")).text'), 'Aé漢😀', 'Reset leaves saved exploration intact')
  await s.input('[data-inspector-input]','e\u0301','input')
  assert.match(await s.text('[data-character-inspector=utf8] [data-inspector-status]'), /2 code points · 3 UTF-8 bytes/)
  await s.input('[data-inspector-input]','A'.repeat(39)+'😀B','input')
  assert.equal(await s.ev('Array.from(document.querySelector("[data-inspector-input]").value).length'),40)
  assert.ok(await s.ev('document.querySelector("[data-inspector-input]").value.endsWith("😀")'))
  await s.input('[data-inspector-input]','<img src=x>','input')
  assert.equal(await s.ev('document.querySelectorAll("[data-character-inspector=utf8] img").length'),0)
  await s.input('[data-inspector-input]','','input')
  assert.match(await s.text('[data-character-inspector=utf8] [data-inspector-status]'), /Enter text/)
  await click('[data-character-inspector=utf8] [data-inspector-reset]')
  await click('[data-action=exit-teacher-mode]')
  // Real keyboard activation remains a button action, not a slide gesture.
  await s.send('Page.bringToFront')
  await s.ev(`document.querySelector('[data-inspector-sample="café"]').focus()`)
  await s.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,text:'\r'})
  await s.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13})
  assert.match(await s.text('[data-character-inspector=utf8] [data-inspector-status]'), /4 code points · 5 UTF-8 bytes/)
  const injected = await s.send('Page.addScriptToEvaluateOnNewDocument',{source:'Object.defineProperty(globalThis,"TextEncoder",{value:undefined,configurable:true})'})
  await s.load('/pages/topics/character-sets-ascii-and-unicode.html','document.querySelector("[data-teacher-opener-slide]")')
  assert.ok(await s.ev('[...document.querySelectorAll("[data-inspector-fallback]")].every(e=>!e.hidden)'))
  assert.equal(await s.ev('document.querySelector("[data-inspector-input]").closest("[data-inspector-controls]").hidden'),true)
  await s.send('Page.removeScriptToEvaluateOnNewDocument',{identifier:injected.identifier})
  assert.deepEqual(s.errors.filter(error=>!error.includes('favicon.ico')),[])
  console.log('PASS character interactions: animated/manual transmission, pause/resume/end/offscreen behavior, shared quiz spacing, ASCII focus, static UTF-8 visual, decoder, saved inspector/keyboard/fallback, compact-slide states.')
} finally { await s.close() }
